#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 06/08/2020 09:25.
HEADER_CLASS_CONFIG_GENERAL = "card-header-primary"
HEADER_CLASS_CONFIG_TECHNICAL = "card-header-primary"
HEADER_CLASS_CONFIG_FINANTIAL = "card-header-primary"
# CONFIG BRAND CUSTOMIZATION
TITLE_VIEW_CONFIG_BRAND = "Marcas"
TITLE_CREATE_CONFIG_BRAND = "Nova Marca"
TITLE_EDIT_CONFIG_BRAND = "Editar Marca"
TITLE_DEL_CONFIG_BRAND = "Deletar Marca"
SUBTITLE_VIEW_CONFIG_BRAND = "Configuração de marcas"
# CONFIG CAPACITY CUSTOMIZATION
TITLE_VIEW_CONFIG_CAPACITY = "Capacidades"
TITLE_CREATE_CONFIG_CAPACITY = "Nova Capacidade"
TITLE_EDIT_CONFIG_CAPACITY = "Editar Capacidade"
TITLE_DEL_CONFIG_CAPACITY = "Deletar Capacidade"
SUBTITLE_VIEW_CONFIG_CAPACITY = "Configuração de capacidades"
# CONFIG MODEL CUSTOMIZATION
TITLE_VIEW_CONFIG_MODEL = "Modelos"
TITLE_CREATE_CONFIG_MODEL = "Novo Modelo"
TITLE_EDIT_CONFIG_MODEL = "Editar Modelo"
TITLE_DEL_CONFIG_MODEL = "Deletar Modelo"
SUBTITLE_VIEW_CONFIG_MODEL = "Configuração de modelos"
# CONFIG TYPE CUSTOMIZATION
TITLE_VIEW_CONFIG_TYPE = "Tipos"
TITLE_CREATE_CONFIG_TYPE = "Novo Tipo"
TITLE_EDIT_CONFIG_TYPE = "Editar Tipo"
TITLE_DEL_CONFIG_TYPE = "Deletar Tipo"
SUBTITLE_VIEW_CONFIG_TYPE = "Configuração de tipos"
# CONFIG CITY CUSTOMIZATION
TITLE_VIEW_CONFIG_CITY = "Cidades"
TITLE_CREATE_CONFIG_CITY = "Nova Cidade"
TITLE_EDIT_CONFIG_CITY = "Editar Cidade"
TITLE_DEL_CONFIG_CITY = "Deletar Cidade"
SUBTITLE_VIEW_CONFIG_CITY = "Configuração de cidades"
# CONFIG TYPE OF SERVICE CUSTOMIZATION
TITLE_VIEW_CONFIG_TYPE_OF_SERVICE = "Tipo de Serviço"
TITLE_CREATE_CONFIG_TYPE_OF_SERVICE = "Novo Tipo de Serviço"
TITLE_EDIT_CONFIG_TYPE_OF_SERVICE = "Editar Tipo de Serviço"
TITLE_DEL_CONFIG_TYPE_OF_SERVICE = "Deletar Tipo de Serviço"
SUBTITLE_VIEW_CONFIG_TYPE_OF_SERVICE = "Configuração de tipos de serviços"
# CONFIG STATUS SERVICE CUSTOMIZATION
TITLE_VIEW_CONFIG_STATUS_SERVICE = "Status do Serviço"
TITLE_CREATE_CONFIG_STATUS_SERVICE = "Novo Status do Serviço"
TITLE_EDIT_CONFIG_STATUS_SERVICE = "Editar Status do Serviço"
TITLE_DEL_CONFIG_STATUS_SERVICE = "Deletar Status do Serviço"
SUBTITLE_VIEW_CONFIG_STATUS_SERVICE = "Configuração de status de serviço"
# CONFIG DEVICE PARTS CUSTOMIZATION
TITLE_VIEW_CONFIG_DEVICE_PARTS = "Peças"
TITLE_CREATE_CONFIG_DEVICE_PARTS = "Nova Peça"
TITLE_EDIT_CONFIG_DEVICE_PARTS = "Editar Peça"
TITLE_DEL_CONFIG_DEVICE_PARTS = "Deletar Peça"
SUBTITLE_VIEW_CONFIG_DEVICE_PARTS = "Configuração de peças"
