#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 10/08/2020 12:49.

# Generated by Django 3.0.2 on 2020-08-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('frontend', '0002_auto_20200810_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsmessages',
            name='important',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsmessages',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
