#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 10/08/2020 13:23.

# Generated by Django 3.0.2 on 2020-08-10 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('config', '0002_auto_20200810_1321'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juridicalcustomer',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou.', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='juridicalcustomer_created_by', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='juridicalcustomer',
            name='devices',
            field=models.ManyToManyField(blank=True, to='device.Device', verbose_name='Equipamentos'),
        ),
        migrations.AddField(
            model_name='juridicalcustomer',
            name='parent_company',
            field=models.ForeignKey(blank=True, help_text='Qual a matriz dessa empresa?', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='customer.JuridicalCustomer',
                                    verbose_name='Matriz'),
        ),
        migrations.AddField(
            model_name='individualcustomer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='config.City', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='individualcustomer',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou.', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='individualcustomer_created_by', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='individualcustomer',
            name='devices',
            field=models.ManyToManyField(blank=True, to='device.Device', verbose_name='Equipamentos'),
        ),
        migrations.AddField(
            model_name='historicaljuridicalcustomer',
            name='city',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='config.City',
                                    verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='historicaljuridicalcustomer',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário que criou.', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='historicaljuridicalcustomer',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljuridicalcustomer',
            name='parent_company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Qual a matriz dessa empresa?',
                                    null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='customer.JuridicalCustomer', verbose_name='Matriz'),
        ),
        migrations.AddField(
            model_name='historicalindividualcustomer',
            name='city',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='config.City',
                                    verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='historicalindividualcustomer',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário que criou.', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='historicalindividualcustomer',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
