#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 24/08/2020 15:54.

# Generated by Django 3.1 on 2020-08-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0002_auto_20200815_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindividualcustomer',
            name='cellphone',
            field=models.CharField(blank=True, max_length=16, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='historicalindividualcustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='historicaljuridicalcustomer',
            name='cellphone',
            field=models.CharField(blank=True, max_length=16, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='historicaljuridicalcustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='individualcustomer',
            name='cellphone',
            field=models.CharField(blank=True, max_length=16, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='individualcustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='juridicalcustomer',
            name='cellphone',
            field=models.CharField(blank=True, max_length=16, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='juridicalcustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='telefone'),
        ),
    ]
