#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 22/07/2020 22:57.

# Generated by Django 3.0.2 on 2020-07-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0003_auto_20200722_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(blank=True,
                                   choices=[('', 'NONE'), ('AC', 'ACRE'), ('AL', 'ALAGOAS'), ('AP', 'AMAPA'),
                                            ('AM', 'AMAZONAS'), ('BA', 'BAHIA'), ('CE', 'CEARA'),
                                            ('DF', 'DISTRITO_FEDERAL'), ('ES', 'ESPIRITO_SANTO'), ('GO', 'GOIAS'),
                                            ('MA', 'MARANHAO'), ('MT', 'MATO_GROSSO'), ('MS', 'MATO_GROSSO_DO_SUL'),
                                            ('MG', 'MINAS_GERAIS'), ('PA', 'PARA'), ('PB', 'PARAIBA'), ('PR', 'PARANA'),
                                            ('PE', 'PERNAMBUCO'), ('PI', 'PIAUI'), ('RJ', 'RIO_DE_JANEIRO'),
                                            ('RN', 'RIO_GRANDE_DO_NORTE'), ('RS', 'RIO_GRANDE_DO_SUL'),
                                            ('RO', 'RONDONIA'), ('RR', 'RORAIMA'), ('SC', 'SANTA_CATARINA'),
                                            ('SP', 'SAO_PAULO'), ('SE', 'SERGIPE'), ('TO', 'TOCANTINS')], max_length=2,
                                   verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='historicalcustomeraddress',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='historicalcustomeraddress',
            name='state',
            field=models.CharField(blank=True,
                                   choices=[('', 'NONE'), ('AC', 'ACRE'), ('AL', 'ALAGOAS'), ('AP', 'AMAPA'),
                                            ('AM', 'AMAZONAS'), ('BA', 'BAHIA'), ('CE', 'CEARA'),
                                            ('DF', 'DISTRITO_FEDERAL'), ('ES', 'ESPIRITO_SANTO'), ('GO', 'GOIAS'),
                                            ('MA', 'MARANHAO'), ('MT', 'MATO_GROSSO'), ('MS', 'MATO_GROSSO_DO_SUL'),
                                            ('MG', 'MINAS_GERAIS'), ('PA', 'PARA'), ('PB', 'PARAIBA'), ('PR', 'PARANA'),
                                            ('PE', 'PERNAMBUCO'), ('PI', 'PIAUI'), ('RJ', 'RIO_DE_JANEIRO'),
                                            ('RN', 'RIO_GRANDE_DO_NORTE'), ('RS', 'RIO_GRANDE_DO_SUL'),
                                            ('RO', 'RONDONIA'), ('RR', 'RORAIMA'), ('SC', 'SANTA_CATARINA'),
                                            ('SP', 'SAO_PAULO'), ('SE', 'SERGIPE'), ('TO', 'TOCANTINS')], max_length=2,
                                   verbose_name='UF'),
        ),
    ]
