#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 24/07/2020 18:57.

# Generated by Django 3.0.2 on 2020-07-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0003_city_historicalcity'),
        ('customer', '0005_auto_20200722_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_line',
            field=models.CharField(blank=True, max_length=256, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='customer',
            name='children_customer',
            field=models.ManyToManyField(to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='config.City', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True,
                                   choices=[('AC', 'ACRE'), ('AL', 'ALAGOAS'), ('AP', 'AMAPA'), ('AM', 'AMAZONAS'),
                                            ('BA', 'BAHIA'), ('CE', 'CEARA'), ('DF', 'DISTRITO_FEDERAL'),
                                            ('ES', 'ESPIRITO_SANTO'), ('GO', 'GOIAS'), ('MA', 'MARANHAO'),
                                            ('MT', 'MATO_GROSSO'), ('MS', 'MATO_GROSSO_DO_SUL'), ('MG', 'MINAS_GERAIS'),
                                            ('PA', 'PARA'), ('PB', 'PARAIBA'), ('PR', 'PARANA'), ('PE', 'PERNAMBUCO'),
                                            ('PI', 'PIAUI'), ('RJ', 'RIO_DE_JANEIRO'), ('RN', 'RIO_GRANDE_DO_NORTE'),
                                            ('RS', 'RIO_GRANDE_DO_SUL'), ('RO', 'RONDONIA'), ('RR', 'RORAIMA'),
                                            ('SC', 'SANTA_CATARINA'), ('SP', 'SAO_PAULO'), ('SE', 'SERGIPE'),
                                            ('TO', 'TOCANTINS')], max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, max_length=128, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='address_line',
            field=models.CharField(blank=True, max_length=256, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='city',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='config.City',
                                    verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='state',
            field=models.CharField(blank=True,
                                   choices=[('AC', 'ACRE'), ('AL', 'ALAGOAS'), ('AP', 'AMAPA'), ('AM', 'AMAZONAS'),
                                            ('BA', 'BAHIA'), ('CE', 'CEARA'), ('DF', 'DISTRITO_FEDERAL'),
                                            ('ES', 'ESPIRITO_SANTO'), ('GO', 'GOIAS'), ('MA', 'MARANHAO'),
                                            ('MT', 'MATO_GROSSO'), ('MS', 'MATO_GROSSO_DO_SUL'), ('MG', 'MINAS_GERAIS'),
                                            ('PA', 'PARA'), ('PB', 'PARAIBA'), ('PR', 'PARANA'), ('PE', 'PERNAMBUCO'),
                                            ('PI', 'PIAUI'), ('RJ', 'RIO_DE_JANEIRO'), ('RN', 'RIO_GRANDE_DO_NORTE'),
                                            ('RS', 'RIO_GRANDE_DO_SUL'), ('RO', 'RONDONIA'), ('RR', 'RORAIMA'),
                                            ('SC', 'SANTA_CATARINA'), ('SP', 'SAO_PAULO'), ('SE', 'SERGIPE'),
                                            ('TO', 'TOCANTINS')], max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='street',
            field=models.CharField(blank=True, max_length=128, verbose_name='Rua'),
        ),
    ]
