#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 17/07/2020 23:30.

# Generated by Django 3.0.2 on 2020-07-18 01:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0007_auto_20200717_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='teste',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='teste',
        ),
    ]
