#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 24/07/2020 18:57.

# Generated by Django 3.0.2 on 2020-07-24 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0007_auto_20200724_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='address',
        ),
    ]
