#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 24/07/2020 18:57.

# Generated by Django 3.0.2 on 2020-07-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0008_auto_20200724_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='children_customer',
            field=models.ManyToManyField(blank=True, help_text='Use para adicionar filiais', to='customer.Customer'),
        ),
    ]
