#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 24/07/2020 18:57.

# Generated by Django 3.0.2 on 2020-07-24 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0009_auto_20200724_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='children_customer',
        ),
    ]
