#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 24/07/2020 18:57.

# Generated by Django 3.0.2 on 2020-07-24 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0010_remove_customer_children_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='parent_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='customer.Customer', verbose_name='Matriz'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='parent_company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='customer.Customer', verbose_name='Matriz'),
        ),
    ]
