#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 24/07/2020 18:57.

# Generated by Django 3.0.2 on 2020-07-24 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0011_auto_20200724_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcustomeraddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='historicalcustomeraddress',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalcustomeraddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='historicalcustomeraddress',
            name='history_user',
        ),
        migrations.AddField(
            model_name='customer',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, verbose_name='Apartamento'),
        ),
        migrations.AddField(
            model_name='customer',
            name='block',
            field=models.CharField(blank=True, max_length=128, verbose_name='Bloco'),
        ),
        migrations.AddField(
            model_name='customer',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=128, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, verbose_name='Apartamento'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='block',
            field=models.CharField(blank=True, max_length=128, verbose_name='Bloco'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=128, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='parent_company',
            field=models.ForeignKey(blank=True, help_text='Qual a matriz dessa empresa?', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer',
                                    verbose_name='Matriz'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='parent_company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Qual a matriz dessa empresa?',
                                    null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='customer.Customer', verbose_name='Matriz'),
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
        migrations.DeleteModel(
            name='HistoricalCustomerAddress',
        ),
    ]
