#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 25/07/2020 16:31.

# Generated by Django 3.0.2 on 2020-07-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0012_auto_20200724_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
    ]
