#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 25/07/2020 23:18.

# Generated by Django 3.0.2 on 2020-07-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0013_auto_20200725_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(blank=True, choices=[('PF', 'FISICA'), ('PJ', 'JURIDICA')], max_length=2,
                                   verbose_name='tipo de pessoa '),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='type',
            field=models.CharField(blank=True, choices=[('PF', 'FISICA'), ('PJ', 'JURIDICA')], max_length=2,
                                   verbose_name='tipo de pessoa '),
        ),
    ]
