#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 25/07/2020 23:18.

# Generated by Django 3.0.2 on 2020-07-26 01:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0003_auto_20200725_2245'),
        ('customer',
         '0016_historicalindividualcustomer_historicaljuridicalcustomer_individualcustomer_juridicalcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='parent_company',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='HistoricalCustomer',
        ),
    ]
