#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 26/07/2020 18:14.

# Generated by Django 3.0.2 on 2020-07-26 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0017_auto_20200725_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juridicalcustomer',
            name='parent_company',
            field=models.ForeignKey(blank=True, help_text='Qual a matriz dessa empresa?', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='customer.JuridicalCustomer',
                                    verbose_name='Matriz'),
        ),
    ]
