#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 28/07/2020 20:57.

# Generated by Django 3.0.2 on 2020-07-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0006_auto_20200728_0954'),
        ('customer', '0018_auto_20200726_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualcustomer',
            name='devices',
            field=models.ManyToManyField(blank=True, to='device.Device', verbose_name='Equipamentos'),
        ),
        migrations.AddField(
            model_name='juridicalcustomer',
            name='devices',
            field=models.ManyToManyField(blank=True, to='device.Device', verbose_name='Equipamentos'),
        ),
    ]
