#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 28/07/2020 20:57.

# Generated by Django 3.0.2 on 2020-07-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0019_auto_20200728_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindividualcustomer',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaljuridicalcustomer',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='individualcustomer',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='juridicalcustomer',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
