#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 02/08/2020 12:00.

# Generated by Django 3.0.2 on 2020-08-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0020_auto_20200728_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindividualcustomer',
            name='phone_1',
            field=models.CharField(blank=True, max_length=15, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='historicalindividualcustomer',
            name='phone_2',
            field=models.CharField(blank=True, max_length=15, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='historicaljuridicalcustomer',
            name='phone_1',
            field=models.CharField(blank=True, max_length=15, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='historicaljuridicalcustomer',
            name='phone_2',
            field=models.CharField(blank=True, max_length=15, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='individualcustomer',
            name='phone_1',
            field=models.CharField(blank=True, max_length=15, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='individualcustomer',
            name='phone_2',
            field=models.CharField(blank=True, max_length=15, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='juridicalcustomer',
            name='phone_1',
            field=models.CharField(blank=True, max_length=15, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='juridicalcustomer',
            name='phone_2',
            field=models.CharField(blank=True, max_length=15, verbose_name='celular'),
        ),
    ]
