# Generated by Django 3.0.2 on 2020-07-12 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateField(auto_now_add=True, help_text='Data em que foi criado.', verbose_name='criado em')),
                ('updated_in', models.DateField(auto_now=True, help_text='Data em que foi atualizado.', verbose_name='atualizado em')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que modificou.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateField(auto_now_add=True, help_text='Data em que foi criado.', verbose_name='criado em')),
                ('updated_in', models.DateField(auto_now=True, help_text='Data em que foi atualizado.', verbose_name='atualizado em')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que modificou.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateField(auto_now_add=True, help_text='Data em que foi criado.', verbose_name='criado em')),
                ('updated_in', models.DateField(auto_now=True, help_text='Data em que foi atualizado.', verbose_name='atualizado em')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que modificou.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateField(auto_now_add=True, help_text='Data em que foi criado.', verbose_name='criado em')),
                ('updated_in', models.DateField(auto_now=True, help_text='Data em que foi atualizado.', verbose_name='atualizado em')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_created_by', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.Unit', verbose_name='Unidade')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que modificou.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateField(auto_now_add=True, help_text='Data em que foi criado.', verbose_name='criado em')),
                ('updated_in', models.DateField(auto_now=True, help_text='Data em que foi atualizado.', verbose_name='atualizado em')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que modificou.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
