#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 17/07/2020 19:36.

# Generated by Django 3.0.2 on 2020-07-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0002_auto_20200717_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantidade'),
        ),
        migrations.AddField(
            model_name='capacity',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantidade'),
        ),
        migrations.AddField(
            model_name='model',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantidade'),
        ),
        migrations.AddField(
            model_name='type',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantidade'),
        ),
        migrations.AddField(
            model_name='unit',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantidade'),
        ),
    ]
