#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 02/08/2020 12:00.

# Generated by Django 3.0.2 on 2020-08-01 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0003_city_historicalcity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in',
                 models.DateField(auto_now_add=True, help_text='Data em que foi criado.', verbose_name='criado em')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou.', null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='typeofservice_created_by', to=settings.AUTH_USER_MODEL,
                                                 verbose_name='Criado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in',
                 models.DateField(auto_now_add=True, help_text='Data em que foi criado.', verbose_name='criado em')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou.', null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='statusservice_created_by', to=settings.AUTH_USER_MODEL,
                                                 verbose_name='Criado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalTypeOfService',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_in', models.DateField(blank=True, editable=False, help_text='Data em que foi criado.',
                                                verbose_name='criado em')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by',
                 models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário que criou.', null=True,
                                   on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical type of service',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStatusService',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_in', models.DateField(blank=True, editable=False, help_text='Data em que foi criado.',
                                                verbose_name='criado em')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by',
                 models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário que criou.', null=True,
                                   on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical status service',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDeviceParts',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_in', models.DateField(blank=True, editable=False, help_text='Data em que foi criado.',
                                                verbose_name='criado em')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by',
                 models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário que criou.', null=True,
                                   on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical device parts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DeviceParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in',
                 models.DateField(auto_now_add=True, help_text='Data em que foi criado.', verbose_name='criado em')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou.', null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='deviceparts_created_by', to=settings.AUTH_USER_MODEL,
                                                 verbose_name='Criado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
