#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 05/08/2020 17:42.

# Generated by Django 3.0.2 on 2020-08-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config',
         '0004_deviceparts_historicaldeviceparts_historicalstatusservice_historicaltypeofservice_statusservice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstatusservice',
            name='badge_class',
            field=models.CharField(blank=True, choices=[('badge-success', 'VERDE'), ('badge-primary', 'AZUL'),
                                                        ('badge-warning', 'AMARELO'), ('badge-danger', 'VERMELHO')],
                                   max_length=20, verbose_name='cor'),
        ),
        migrations.AddField(
            model_name='statusservice',
            name='badge_class',
            field=models.CharField(blank=True, choices=[('badge-success', 'VERDE'), ('badge-primary', 'AZUL'),
                                                        ('badge-warning', 'AMARELO'), ('badge-danger', 'VERMELHO')],
                                   max_length=20, verbose_name='cor'),
        ),
    ]
