#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 05/08/2020 19:01.

# Generated by Django 3.0.2 on 2020-08-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0005_auto_20200805_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstatusservice',
            name='badge_class',
            field=models.CharField(blank=True, choices=[('badge-success', 'VERDE'), ('badge-primary', 'AZUL'),
                                                        ('badge-info', 'CIANO'), ('badge-warning', 'AMARELO'),
                                                        ('badge-danger', 'VERMELHO'), ('badge-default', 'CINZA')],
                                   max_length=20, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='statusservice',
            name='badge_class',
            field=models.CharField(blank=True, choices=[('badge-success', 'VERDE'), ('badge-primary', 'AZUL'),
                                                        ('badge-info', 'CIANO'), ('badge-warning', 'AMARELO'),
                                                        ('badge-danger', 'VERMELHO'), ('badge-default', 'CINZA')],
                                   max_length=20, verbose_name='cor'),
        ),
    ]
