#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 18/07/2020 12:03.

# Generated by Django 3.0.2 on 2020-07-18 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0009_historicalbrand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalBrand',
        ),
    ]
