#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 18/07/2020 12:03.

# Generated by Django 3.0.2 on 2020-07-18 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0012_historicalcapacity_historicalmodel_historicaltype_historicalunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='updated_in',
        ),
        migrations.RemoveField(
            model_name='capacity',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='capacity',
            name='updated_in',
        ),
        migrations.RemoveField(
            model_name='historicalbrand',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalbrand',
            name='updated_in',
        ),
        migrations.RemoveField(
            model_name='historicalcapacity',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalcapacity',
            name='updated_in',
        ),
        migrations.RemoveField(
            model_name='historicalmodel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalmodel',
            name='updated_in',
        ),
        migrations.RemoveField(
            model_name='historicaltype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicaltype',
            name='updated_in',
        ),
        migrations.RemoveField(
            model_name='historicalunit',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalunit',
            name='updated_in',
        ),
        migrations.RemoveField(
            model_name='model',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='model',
            name='updated_in',
        ),
        migrations.RemoveField(
            model_name='type',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='type',
            name='updated_in',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='updated_in',
        ),
    ]
