#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 02/08/2020 12:00.

# Generated by Django 3.0.2 on 2020-08-02 13:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('config',
         '0004_deviceparts_historicaldeviceparts_historicalstatusservice_historicaltypeofservice_statusservice_type'),
        ('device', '0007_auto_20200731_1306'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in',
                 models.DateField(auto_now_add=True, help_text='Data em que foi criado.', verbose_name='criado em')),
                ('start_date', models.DateField(default=datetime.datetime.today, verbose_name='data de início')),
                ('end_date', models.DateField(blank=True, verbose_name='data de término')),
                ('defect', models.TextField(blank=True, verbose_name='defeito')),
                ('observation', models.TextField(blank=True, verbose_name='observação')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou.', null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='orderofservice_created_by', to=settings.AUTH_USER_MODEL,
                                                 verbose_name='Criado por')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device',
                                             verbose_name='Equipamento')),
                ('parts', models.ManyToManyField(null=True, to='config.DeviceParts', verbose_name='Peças')),
                ('status',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.StatusService',
                                   verbose_name='Status')),
                ('type_of_service',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.TypeOfService',
                                   verbose_name='Tipo de Serviço')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrderOfService',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_in', models.DateField(blank=True, editable=False, help_text='Data em que foi criado.',
                                                verbose_name='criado em')),
                ('start_date', models.DateField(default=datetime.datetime.today, verbose_name='data de início')),
                ('end_date', models.DateField(blank=True, verbose_name='data de término')),
                ('defect', models.TextField(blank=True, verbose_name='defeito')),
                ('observation', models.TextField(blank=True, verbose_name='observação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by',
                 models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário que criou.', null=True,
                                   on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                             on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                             to='device.Device', verbose_name='Equipamento')),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                             on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                             to='config.StatusService', verbose_name='Status')),
                ('type_of_service', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                      on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                      to='config.TypeOfService', verbose_name='Tipo de Serviço')),
            ],
            options={
                'verbose_name': 'historical order of service',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
