#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 02/08/2020 12:00.

# Generated by Django 3.0.2 on 2020-08-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config',
         '0004_deviceparts_historicaldeviceparts_historicalstatusservice_historicaltypeofservice_statusservice_type'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofservice',
            name='parts',
            field=models.ManyToManyField(blank=True, to='config.DeviceParts', verbose_name='Peças'),
        ),
    ]
