#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 15/08/2020 15:57.

# Generated by Django 3.0.2 on 2020-08-15 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('config', '0002_auto_20200815_1547'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsexchanged',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou.', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='partsexchanged_created_by', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='partsexchanged',
            name='order_of_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='service.OrderOfService', verbose_name='Ordem de Serviço'),
        ),
        migrations.AddField(
            model_name='partsexchanged',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.DeviceParts',
                                    verbose_name='Peça'),
        ),
        migrations.AddField(
            model_name='orderofservice',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou.', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='orderofservice_created_by', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='orderofservice',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.StatusService',
                                    verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='orderofservice',
            name='type_of_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.TypeOfService',
                                    verbose_name='Tipo de Serviço'),
        ),
        migrations.AddField(
            model_name='historicalpartsexchanged',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário que criou.', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='historicalpartsexchanged',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpartsexchanged',
            name='order_of_service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='service.OrderOfService', verbose_name='Ordem de Serviço'),
        ),
        migrations.AddField(
            model_name='historicalpartsexchanged',
            name='part',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='config.DeviceParts', verbose_name='Peça'),
        ),
        migrations.AddField(
            model_name='historicalorderofservice',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário que criou.', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='historicalorderofservice',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalorderofservice',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='config.StatusService', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='historicalorderofservice',
            name='type_of_service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='config.TypeOfService', verbose_name='Tipo de Serviço'),
        ),
    ]
