#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 02/08/2020 12:00.

# Generated by Django 3.0.2 on 2020-08-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0003_auto_20200802_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderofservice',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de término'),
        ),
        migrations.AlterField(
            model_name='orderofservice',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de término'),
        ),
    ]
