#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 02/08/2020 12:00.

# Generated by Django 3.0.2 on 2020-08-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0007_auto_20200731_1306'),
        ('service', '0004_auto_20200802_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderofservice',
            name='device',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='device.Device', verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='orderofservice',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Device',
                                    verbose_name='Equipamento'),
        ),
    ]
