#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 05/08/2020 17:42.

# Generated by Django 3.0.2 on 2020-08-02 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('config',
         '0004_deviceparts_historicaldeviceparts_historicalstatusservice_historicaltypeofservice_statusservice_type'),
        ('service', '0007_auto_20200802_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderofservice',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='config.StatusService', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderofservice',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.StatusService',
                                    verbose_name='Status'),
        ),
    ]
