#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 07/08/2020 15:06.

# Generated by Django 3.0.2 on 2020-08-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0011_auto_20200806_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofservice',
            name='parts',
            field=models.ManyToManyField(blank=True, to='service.PartsExchanged', verbose_name='Peças'),
        ),
    ]
