#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 09/08/2020 11:09.

# Generated by Django 3.0.2 on 2020-08-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0012_auto_20200806_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartsexchanged',
            name='order_of_service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='service.OrderOfService'),
        ),
        migrations.AddField(
            model_name='partsexchanged',
            name='order_of_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='service.OrderOfService'),
        ),
        migrations.AlterField(
            model_name='historicalpartsexchanged',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='partsexchanged',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
