#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 09/08/2020 11:09.

# Generated by Django 3.0.2 on 2020-08-09 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0016_auto_20200808_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderofservice',
            name='parts',
        ),
        migrations.AlterField(
            model_name='historicalpartsexchanged',
            name='order_of_service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='service.OrderOfService', verbose_name='Ordem de Serviço'),
        ),
        migrations.AlterField(
            model_name='partsexchanged',
            name='order_of_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.OrderOfService',
                                    verbose_name='Ordem de Serviço'),
        ),
    ]
