#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 09/08/2020 11:09.

# Generated by Django 3.0.2 on 2020-08-09 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0017_auto_20200808_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsexchanged',
            name='order_of_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='service.OrderOfService', verbose_name='Ordem de Serviço'),
        ),
    ]
