#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 09/08/2020 11:09.

# Generated by Django 3.0.2 on 2020-08-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0006_auto_20200805_1900'),
        ('service', '0018_auto_20200808_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsexchanged',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='config.DeviceParts', verbose_name='Peça'),
        ),
    ]
