#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 09/08/2020 11:09.

# Generated by Django 3.0.2 on 2020-08-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0019_auto_20200809_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpartsexchanged',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='partsexchanged',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantidade'),
        ),
    ]
