#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 09/08/2020 22:11.

# Generated by Django 3.0.2 on 2020-08-10 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0021_auto_20200809_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorderofservice',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='historicalorderofservice',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='orderofservice',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='orderofservice',
            name='start_date',
        ),
        migrations.AddField(
            model_name='historicalorderofservice',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='orderofservice',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Data'),
        ),
    ]
