#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 12/07/2020 20:01.

# Generated by Django 3.0.2 on 2020-07-12 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_auto_20200710_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateField(auto_now_add=True, help_text='Data em que foi criado.', verbose_name='criado em')),
                ('updated_in', models.DateField(auto_now=True, help_text='Data em que foi atualizado.', verbose_name='atualizado em')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='nome')),
                ('patrimony', models.CharField(blank=True, max_length=128, verbose_name='patrimônio')),
                ('entry_date', models.DateField(blank=True, verbose_name='data de entrada')),
                ('departure_date', models.DateField(blank=True, verbose_name='data de saída')),
                ('observation', models.TextField(blank=True, verbose_name='observações')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.Brand', verbose_name='Marca')),
                ('capacity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.Capacity', verbose_name='Capacidade')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='Cliente')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.Model', verbose_name='Modelo')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.Type', verbose_name='Tipo')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que modificou.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
