#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 15/08/2020 15:57.

# Generated by Django 3.0.2 on 2020-08-15 18:47

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in',
                 models.DateField(auto_now_add=True, help_text='Data em que foi criado.', verbose_name='criado em')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='nome')),
                ('identifier', models.CharField(blank=True, max_length=128, verbose_name='identificador')),
                ('patrimony', models.CharField(blank=True, max_length=128, verbose_name='patrimônio')),
                ('observation', models.TextField(blank=True, verbose_name='observações')),
                ('location', models.TextField(blank=True, verbose_name='localização')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalDevice',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_in', models.DateField(blank=True, editable=False, help_text='Data em que foi criado.',
                                                verbose_name='criado em')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='nome')),
                ('identifier', models.CharField(blank=True, max_length=128, verbose_name='identificador')),
                ('patrimony', models.CharField(blank=True, max_length=128, verbose_name='patrimônio')),
                ('observation', models.TextField(blank=True, verbose_name='observações')),
                ('location', models.TextField(blank=True, verbose_name='localização')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('brand', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                            on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                            to='config.Brand', verbose_name='Marca')),
                ('capacity', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                               on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                               to='config.Capacity', verbose_name='Capacidade')),
            ],
            options={
                'verbose_name': 'historical device',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
