#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 25/07/2020 23:18.

# Generated by Django 3.0.2 on 2020-07-26 01:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0002_auto_20200718_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='customer',
        ),
    ]
