#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 28/07/2020 10:04.

# Generated by Django 3.0.2 on 2020-07-28 11:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0018_auto_20200726_1607'),
        ('device', '0003_auto_20200725_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='individual_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='customer.IndividualCustomer', verbose_name='Pessoa Física'),
        ),
        migrations.AddField(
            model_name='device',
            name='juridical_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='customer.JuridicalCustomer', verbose_name='Pessoa Jurídica'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.TextField(blank=True, verbose_name='localização'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='individual_customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='customer.IndividualCustomer', verbose_name='Pessoa Física'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='juridical_customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='customer.JuridicalCustomer', verbose_name='Pessoa Jurídica'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='location',
            field=models.TextField(blank=True, verbose_name='localização'),
        ),
        migrations.AlterField(
            model_name='device',
            name='entry_date',
            field=models.DateField(blank=True, default=datetime.datetime.today, verbose_name='data de entrada'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='entry_date',
            field=models.DateField(blank=True, default=datetime.datetime.today, verbose_name='data de entrada'),
        ),
    ]
