#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 28/07/2020 10:04.

# Generated by Django 3.0.2 on 2020-07-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0004_auto_20200728_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de saída'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de saída'),
        ),
    ]
