#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 28/07/2020 10:04.

# Generated by Django 3.0.2 on 2020-07-28 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0005_auto_20200728_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='individual_customer',
        ),
        migrations.RemoveField(
            model_name='device',
            name='juridical_customer',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='individual_customer',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='juridical_customer',
        ),
    ]
