#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 18/07/2020 12:03.

# Generated by Django 3.0.2 on 2020-07-18 14:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0009_historicaladdress_historicalcustomer'),
        ('config', '0012_historicalcapacity_historicalmodel_historicaltype_historicalunit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0006_remove_device_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDevice',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_in', models.DateField(blank=True, editable=False, help_text='Data em que foi criado.',
                                                verbose_name='criado em')),
                ('updated_in', models.DateField(blank=True, editable=False, help_text='Data em que foi atualizado.',
                                                verbose_name='atualizado em')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='nome')),
                ('patrimony', models.CharField(blank=True, max_length=128, verbose_name='patrimônio')),
                ('entry_date', models.DateField(blank=True, verbose_name='data de entrada')),
                ('departure_date', models.DateField(blank=True, verbose_name='data de saída')),
                ('observation', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('brand', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                            on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                            to='config.Brand', verbose_name='Marca')),
                ('capacity', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                               on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                               to='config.Capacity', verbose_name='Capacidade')),
                ('created_by',
                 models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário que criou.', null=True,
                                   on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                               on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                               to='customer.Customer', verbose_name='Cliente')),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                            on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                            to='config.Model', verbose_name='Modelo')),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                           on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                           to='config.Type', verbose_name='Tipo')),
                ('updated_by',
                 models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário que modificou.', null=True,
                                   on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'historical device',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
