#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 31/07/2020 13:53.

# Generated by Django 3.0.2 on 2020-07-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0006_auto_20200728_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='identifier',
            field=models.CharField(blank=True, max_length=128, verbose_name='identificador'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='identifier',
            field=models.CharField(blank=True, max_length=128, verbose_name='identificador'),
        ),
    ]
