#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 18/07/2020 12:03.

# Generated by Django 3.0.2 on 2020-07-18 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0007_historicaldevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='device',
            name='updated_in',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='updated_in',
        ),
    ]
