#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 02/08/2020 12:00.

# Generated by Django 3.0.2 on 2020-08-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0006_auto_20200802_1032'),
        ('device', '0007_auto_20200731_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='order_of_services',
            field=models.ManyToManyField(blank=True, to='service.OrderOfService', verbose_name='Ordem de Serviços'),
        ),
    ]
