#  Created by Alex Matos Iuasse.
#  Copyright (c) 2020.  All rights reserved.
#  Last modified 07/08/2020 15:06.

# Generated by Django 3.0.2 on 2020-08-06 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0008_device_order_of_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='entry_date',
        ),
    ]
